//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WS_SR
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="City", Namespace="http://tempuri.org/")]
    public partial class City : object
    {
        
        private int IdField;
        
        private string NameField;
        
        private string CountryCodeField;
        
        private string DistrictField;
        
        private int PopulationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CountryCode
        {
            get
            {
                return this.CountryCodeField;
            }
            set
            {
                this.CountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string District
        {
            get
            {
                return this.DistrictField;
            }
            set
            {
                this.DistrictField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Population
        {
            get
            {
                return this.PopulationField;
            }
            set
            {
                this.PopulationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Country", Namespace="http://tempuri.org/")]
    public partial class Country : object
    {
        
        private string CodeField;
        
        private string NameField;
        
        private string ContinentField;
        
        private string RegionField;
        
        private float SurfaceAreaField;
        
        private long PopulationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Continent
        {
            get
            {
                return this.ContinentField;
            }
            set
            {
                this.ContinentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Region
        {
            get
            {
                return this.RegionField;
            }
            set
            {
                this.RegionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public float SurfaceArea
        {
            get
            {
                return this.SurfaceAreaField;
            }
            set
            {
                this.SurfaceAreaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public long Population
        {
            get
            {
                return this.PopulationField;
            }
            set
            {
                this.PopulationField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WS_SR.CityWSSoap")]
    public interface CityWSSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getAllCities", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_SR.getAllCitiesResponse> getAllCitiesAsync(WS_SR.getAllCitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountryByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_SR.GetCountryByCodeResponse> GetCountryByCodeAsync(WS_SR.GetCountryByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCityByName", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_SR.GetCityByNameResponse> GetCityByNameAsync(WS_SR.GetCityByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCitiesByCountry", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_SR.GetCitiesByCountryResponse> GetCitiesByCountryAsync(WS_SR.GetCitiesByCountryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCountriesByPopulation", ReplyAction="*")]
        System.Threading.Tasks.Task<WS_SR.GetCountriesByPopulationResponse> GetCountriesByPopulationAsync(WS_SR.GetCountriesByPopulationRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllCitiesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllCities", Namespace="http://tempuri.org/", Order=0)]
        public WS_SR.getAllCitiesRequestBody Body;
        
        public getAllCitiesRequest()
        {
        }
        
        public getAllCitiesRequest(WS_SR.getAllCitiesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getAllCitiesRequestBody
    {
        
        public getAllCitiesRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAllCitiesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAllCitiesResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_SR.getAllCitiesResponseBody Body;
        
        public getAllCitiesResponse()
        {
        }
        
        public getAllCitiesResponse(WS_SR.getAllCitiesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getAllCitiesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_SR.City[] getAllCitiesResult;
        
        public getAllCitiesResponseBody()
        {
        }
        
        public getAllCitiesResponseBody(WS_SR.City[] getAllCitiesResult)
        {
            this.getAllCitiesResult = getAllCitiesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountryByCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountryByCode", Namespace="http://tempuri.org/", Order=0)]
        public WS_SR.GetCountryByCodeRequestBody Body;
        
        public GetCountryByCodeRequest()
        {
        }
        
        public GetCountryByCodeRequest(WS_SR.GetCountryByCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountryByCodeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string countryCode;
        
        public GetCountryByCodeRequestBody()
        {
        }
        
        public GetCountryByCodeRequestBody(string countryCode)
        {
            this.countryCode = countryCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountryByCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountryByCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_SR.GetCountryByCodeResponseBody Body;
        
        public GetCountryByCodeResponse()
        {
        }
        
        public GetCountryByCodeResponse(WS_SR.GetCountryByCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountryByCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_SR.Country GetCountryByCodeResult;
        
        public GetCountryByCodeResponseBody()
        {
        }
        
        public GetCountryByCodeResponseBody(WS_SR.Country GetCountryByCodeResult)
        {
            this.GetCountryByCodeResult = GetCountryByCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityByNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityByName", Namespace="http://tempuri.org/", Order=0)]
        public WS_SR.GetCityByNameRequestBody Body;
        
        public GetCityByNameRequest()
        {
        }
        
        public GetCityByNameRequest(WS_SR.GetCityByNameRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCityByNameRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cityName;
        
        public GetCityByNameRequestBody()
        {
        }
        
        public GetCityByNameRequestBody(string cityName)
        {
            this.cityName = cityName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCityByNameResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCityByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_SR.GetCityByNameResponseBody Body;
        
        public GetCityByNameResponse()
        {
        }
        
        public GetCityByNameResponse(WS_SR.GetCityByNameResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCityByNameResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_SR.City GetCityByNameResult;
        
        public GetCityByNameResponseBody()
        {
        }
        
        public GetCityByNameResponseBody(WS_SR.City GetCityByNameResult)
        {
            this.GetCityByNameResult = GetCityByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCitiesByCountryRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCitiesByCountry", Namespace="http://tempuri.org/", Order=0)]
        public WS_SR.GetCitiesByCountryRequestBody Body;
        
        public GetCitiesByCountryRequest()
        {
        }
        
        public GetCitiesByCountryRequest(WS_SR.GetCitiesByCountryRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCitiesByCountryRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string countryCode;
        
        public GetCitiesByCountryRequestBody()
        {
        }
        
        public GetCitiesByCountryRequestBody(string countryCode)
        {
            this.countryCode = countryCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCitiesByCountryResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCitiesByCountryResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_SR.GetCitiesByCountryResponseBody Body;
        
        public GetCitiesByCountryResponse()
        {
        }
        
        public GetCitiesByCountryResponse(WS_SR.GetCitiesByCountryResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCitiesByCountryResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_SR.City[] GetCitiesByCountryResult;
        
        public GetCitiesByCountryResponseBody()
        {
        }
        
        public GetCitiesByCountryResponseBody(WS_SR.City[] GetCitiesByCountryResult)
        {
            this.GetCitiesByCountryResult = GetCitiesByCountryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesByPopulationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountriesByPopulation", Namespace="http://tempuri.org/", Order=0)]
        public WS_SR.GetCountriesByPopulationRequestBody Body;
        
        public GetCountriesByPopulationRequest()
        {
        }
        
        public GetCountriesByPopulationRequest(WS_SR.GetCountriesByPopulationRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountriesByPopulationRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long populationThreshold;
        
        public GetCountriesByPopulationRequestBody()
        {
        }
        
        public GetCountriesByPopulationRequestBody(long populationThreshold)
        {
            this.populationThreshold = populationThreshold;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCountriesByPopulationResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCountriesByPopulationResponse", Namespace="http://tempuri.org/", Order=0)]
        public WS_SR.GetCountriesByPopulationResponseBody Body;
        
        public GetCountriesByPopulationResponse()
        {
        }
        
        public GetCountriesByPopulationResponse(WS_SR.GetCountriesByPopulationResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCountriesByPopulationResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WS_SR.Country[] GetCountriesByPopulationResult;
        
        public GetCountriesByPopulationResponseBody()
        {
        }
        
        public GetCountriesByPopulationResponseBody(WS_SR.Country[] GetCountriesByPopulationResult)
        {
            this.GetCountriesByPopulationResult = GetCountriesByPopulationResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface CityWSSoapChannel : WS_SR.CityWSSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class CityWSSoapClient : System.ServiceModel.ClientBase<WS_SR.CityWSSoap>, WS_SR.CityWSSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CityWSSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CityWSSoapClient.GetBindingForEndpoint(endpointConfiguration), CityWSSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CityWSSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CityWSSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CityWSSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CityWSSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CityWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_SR.getAllCitiesResponse> WS_SR.CityWSSoap.getAllCitiesAsync(WS_SR.getAllCitiesRequest request)
        {
            return base.Channel.getAllCitiesAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_SR.getAllCitiesResponse> getAllCitiesAsync()
        {
            WS_SR.getAllCitiesRequest inValue = new WS_SR.getAllCitiesRequest();
            inValue.Body = new WS_SR.getAllCitiesRequestBody();
            return ((WS_SR.CityWSSoap)(this)).getAllCitiesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_SR.GetCountryByCodeResponse> WS_SR.CityWSSoap.GetCountryByCodeAsync(WS_SR.GetCountryByCodeRequest request)
        {
            return base.Channel.GetCountryByCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_SR.GetCountryByCodeResponse> GetCountryByCodeAsync(string countryCode)
        {
            WS_SR.GetCountryByCodeRequest inValue = new WS_SR.GetCountryByCodeRequest();
            inValue.Body = new WS_SR.GetCountryByCodeRequestBody();
            inValue.Body.countryCode = countryCode;
            return ((WS_SR.CityWSSoap)(this)).GetCountryByCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_SR.GetCityByNameResponse> WS_SR.CityWSSoap.GetCityByNameAsync(WS_SR.GetCityByNameRequest request)
        {
            return base.Channel.GetCityByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_SR.GetCityByNameResponse> GetCityByNameAsync(string cityName)
        {
            WS_SR.GetCityByNameRequest inValue = new WS_SR.GetCityByNameRequest();
            inValue.Body = new WS_SR.GetCityByNameRequestBody();
            inValue.Body.cityName = cityName;
            return ((WS_SR.CityWSSoap)(this)).GetCityByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_SR.GetCitiesByCountryResponse> WS_SR.CityWSSoap.GetCitiesByCountryAsync(WS_SR.GetCitiesByCountryRequest request)
        {
            return base.Channel.GetCitiesByCountryAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_SR.GetCitiesByCountryResponse> GetCitiesByCountryAsync(string countryCode)
        {
            WS_SR.GetCitiesByCountryRequest inValue = new WS_SR.GetCitiesByCountryRequest();
            inValue.Body = new WS_SR.GetCitiesByCountryRequestBody();
            inValue.Body.countryCode = countryCode;
            return ((WS_SR.CityWSSoap)(this)).GetCitiesByCountryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WS_SR.GetCountriesByPopulationResponse> WS_SR.CityWSSoap.GetCountriesByPopulationAsync(WS_SR.GetCountriesByPopulationRequest request)
        {
            return base.Channel.GetCountriesByPopulationAsync(request);
        }
        
        public System.Threading.Tasks.Task<WS_SR.GetCountriesByPopulationResponse> GetCountriesByPopulationAsync(long populationThreshold)
        {
            WS_SR.GetCountriesByPopulationRequest inValue = new WS_SR.GetCountriesByPopulationRequest();
            inValue.Body = new WS_SR.GetCountriesByPopulationRequestBody();
            inValue.Body.populationThreshold = populationThreshold;
            return ((WS_SR.CityWSSoap)(this)).GetCountriesByPopulationAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CityWSSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CityWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CityWSSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44342/api/CityWS.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.CityWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44342/api/CityWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CityWSSoap,
            
            CityWSSoap12,
        }
    }
}
